version: '3.8'
services:
  # 服务名
  dev-db:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: next
