import './globals.css'
import { Inter } from 'next/font/google'

import Sidebar from './components/Sidebar'
import ClientOnly from './components/ClientOnly'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bill',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          <ClientOnly>
            <Sidebar />
          </ClientOnly>
          <div className='w-full p-4'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
